import type { ReportSection } from './anthropic'
import type { Incident } from './incidents'

const NDMA_EMAIL = 'ndma-disastermind@gov.in'

export interface ReportExportData {
  incident: Incident
  audience: string
  generatedAt: Date
  sections: ReportSection[]
}

function formatGeneratedAt(date: Date): string {
  return new Intl.DateTimeFormat('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
    timeZone: 'Asia/Kolkata',
  }).format(date)
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

function reportTitle({ incident }: ReportExportData): string {
  return `${incident.disaster} — ${incident.location} (${incident.month})`
}

/** Print-friendly (light) HTML document of the rendered report. */
function buildPrintableHtml(data: ReportExportData): string {
  const { audience, generatedAt, sections } = data
  const sectionHtml = sections
    .map((section) => {
      const paragraphs = section.body
        .split(/\n+/)
        .filter((p) => p.trim())
        .map((p) => `<p>${escapeHtml(p)}</p>`)
        .join('')
      return `<section><h2>${escapeHtml(section.title)}</h2><div class="rule"></div>${paragraphs}</section>`
    })
    .join('')

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>DisasterMind — ${escapeHtml(reportTitle(data))}</title>
<style>
  @page { margin: 18mm 16mm; }
  * { box-sizing: border-box; }
  body { font-family: 'Hanken Grotesk', system-ui, sans-serif; color: #14110c; font-size: 12px; line-height: 1.6; max-width: 820px; margin: 0 auto; padding: 24px; }
  .doc-head { border-bottom: 2px solid #10b981; padding-bottom: 14px; margin-bottom: 22px; }
  .eyebrow { font-size: 10px; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase; color: #047857; margin: 0 0 6px; }
  h1 { font-size: 22px; font-weight: 700; margin: 0 0 6px; letter-spacing: -0.01em; }
  .meta { font-size: 10px; color: #6b7280; font-family: ui-monospace, monospace; }
  h2 { font-size: 13px; font-weight: 700; letter-spacing: 0.04em; text-transform: uppercase; color: #065f46; margin: 22px 0 4px; }
  .rule { height: 2px; width: 48px; background: #10b981; border-radius: 2px; margin-bottom: 10px; }
  p { margin: 0 0 8px; }
  .doc-foot { margin-top: 28px; padding-top: 14px; border-top: 1px solid #d1d5db; font-size: 10px; color: #6b7280; text-align: center; }
</style>
</head>
<body>
  <div class="doc-head">
    <p class="eyebrow">DisasterMind // Post-Incident Analysis Report</p>
    <h1>${escapeHtml(reportTitle(data))}</h1>
    <div class="meta">Classification: Official &middot; Generated ${escapeHtml(formatGeneratedAt(generatedAt))} IST &middot; Audience: ${escapeHtml(audience)}</div>
  </div>
  ${sectionHtml}
  <div class="doc-foot">
    <p>This report was generated by DisasterMind AI v1.0. All autonomous decisions are logged in the tamper-proof audit trail.</p>
    <p>For queries: ${NDMA_EMAIL}</p>
  </div>
</body>
</html>`
}

/**
 * "Download PDF" — opens the print dialog on a print-ready rendering of the
 * report, where the user picks "Save as PDF". Dependency-free and works in
 * every browser. Falls back to a hidden iframe if the popup is blocked.
 */
export function downloadReportPdf(data: ReportExportData): void {
  const html = buildPrintableHtml(data)
  const printWindow = window.open('', '_blank')

  if (printWindow) {
    printWindow.document.write(html)
    printWindow.document.close()
    printWindow.focus()
    // Give fonts/layout a tick to settle before invoking print.
    window.setTimeout(() => printWindow.print(), 250)
    return
  }

  // Popup blocked → print via a hidden iframe in the current document.
  const iframe = document.createElement('iframe')
  iframe.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0;'
  document.body.appendChild(iframe)
  const doc = iframe.contentWindow?.document
  if (!doc) return
  doc.open()
  doc.write(html)
  doc.close()
  iframe.onload = () => {
    iframe.contentWindow?.focus()
    iframe.contentWindow?.print()
    window.setTimeout(() => document.body.removeChild(iframe), 1500)
  }
}

/** Plain-text summary used as the email body for the NDMA dispatch. */
function buildPlainText(data: ReportExportData): string {
  const { incident, audience, generatedAt, sections } = data
  const header = [
    'DISASTERMIND // POST-INCIDENT ANALYSIS REPORT',
    reportTitle(data),
    `Classification: OFFICIAL | Generated: ${formatGeneratedAt(generatedAt)} IST | Audience: ${audience}`,
    `Civilians reached: ${incident.civiliansReached.toLocaleString('en-IN')} of ${incident.civiliansAtRisk.toLocaleString('en-IN')} at risk`,
    '',
  ].join('\n')

  const body = sections
    .map((s) => `## ${s.title}\n${s.body.trim()}`)
    .join('\n\n')

  return `${header}\n${body}\n\n— Generated by DisasterMind AI v1.0`
}

/**
 * "Send to NDMA" — opens the operator's mail client with a dispatch to the
 * NDMA desk pre-filled (recipient, subject, plain-text report body). mailto
 * bodies are length-limited across clients, so the body is capped and the
 * full document is referenced as the attachable PDF.
 */
export function sendReportToNdma(data: ReportExportData): void {
  const subject = `[DisasterMind] Post-Incident Report — ${reportTitle(data)}`
  const full = buildPlainText(data)
  // Keep well under the ~2000-char practical mailto ceiling.
  const MAX = 1600
  const body =
    full.length > MAX
      ? `${full.slice(0, MAX)}\n\n…[truncated — attach the downloaded PDF for the full report]`
      : full

  const href = `mailto:${NDMA_EMAIL}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
  window.location.href = href
}
