import type { ReportSection } from './anthropic'
import type { Incident } from './incidents'
import type { SiteEvidenceImage } from './siteEvidence'

const NDMA_EMAIL = 'ndma-disastermind@gov.in'

export interface ReportExportData {
  incident: Incident
  audience: string
  generatedAt: Date
  sections: ReportSection[]
  siteEvidence: SiteEvidenceImage[]
}

function formatGeneratedAt(date: Date): string {
  return new Intl.DateTimeFormat('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
    timeZone: 'Asia/Kolkata',
  }).format(date)
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

function reportTitle({ incident }: ReportExportData): string {
  return `${incident.disaster} — ${incident.location} (${incident.month})`
}

/** Print-friendly (light) HTML document of the rendered report. */
function buildPrintableHtml(data: ReportExportData, evidenceSources: string[]): string {
  const { audience, generatedAt, sections, siteEvidence } = data
  const sectionHtml = sections
    .map((section) => {
      const paragraphs = section.body
        .split(/\n+/)
        .filter((p) => p.trim())
        .map((p) => `<p>${escapeHtml(p)}</p>`)
        .join('')
      return `<section><h2>${escapeHtml(section.title)}</h2><div class="rule"></div>${paragraphs}</section>`
    })
    .join('')
  const evidenceHtml = siteEvidence.length > 0
    ? `<section class="evidence"><h2>AFFECTED SITE EVIDENCE</h2><div class="rule"></div><p class="evidence-note">Reviewer-selected field imagery. Categories and metadata are manually supplied and have not been inferred from image content.</p><div class="evidence-grid">${siteEvidence.map((image, index) => {
      const metadata = [
        image.location || 'Location not provided',
        image.timestamp,
        image.latitude && image.longitude ? `${image.latitude}, ${image.longitude}` : undefined,
      ].filter(Boolean).map((value) => `<span>${escapeHtml(value!)}</span>`).join('')
      return `<figure><img src="${evidenceSources[index]}" alt=""><figcaption><strong>${escapeHtml(image.category || 'NOT CLASSIFIED')}</strong>${metadata}${image.note ? `<p>${escapeHtml(image.note)}</p>` : ''}<small>${escapeHtml(image.filename)}</small></figcaption></figure>`
    }).join('')}</div></section>`
    : ''

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>DisasterMind — ${escapeHtml(reportTitle(data))}</title>
<style>
  @page { margin: 18mm 16mm; }
  * { box-sizing: border-box; }
  body { font-family: 'Hanken Grotesk', system-ui, sans-serif; color: #14110c; font-size: 12px; line-height: 1.6; max-width: 820px; margin: 0 auto; padding: 24px; }
  .doc-head { border-bottom: 2px solid #10b981; padding-bottom: 14px; margin-bottom: 22px; }
  .eyebrow { font-size: 10px; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase; color: #047857; margin: 0 0 6px; }
  h1 { font-size: 22px; font-weight: 700; margin: 0 0 6px; letter-spacing: -0.01em; }
  .meta { font-size: 10px; color: #6b7280; font-family: ui-monospace, monospace; }
  h2 { font-size: 13px; font-weight: 700; letter-spacing: 0.04em; text-transform: uppercase; color: #065f46; margin: 22px 0 4px; }
  .rule { height: 2px; width: 48px; background: #10b981; border-radius: 2px; margin-bottom: 10px; }
  p { margin: 0 0 8px; }
  .evidence-note { color: #6b7280; font-size: 10px; }
  .evidence-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 14px; margin-top: 12px; }
  figure { margin: 0; break-inside: avoid; border: 1px solid #d1d5db; }
  figure img { display: block; width: 100%; height: 180px; object-fit: cover; }
  figcaption { display: flex; flex-direction: column; gap: 2px; padding: 8px; font-family: ui-monospace, monospace; font-size: 9px; }
  figcaption strong { color: #047857; letter-spacing: 0.05em; }
  figcaption span, figcaption small { color: #6b7280; }
  figcaption p { margin-top: 4px; font-family: 'Hanken Grotesk', system-ui, sans-serif; font-size: 10px; }
  .doc-foot { margin-top: 28px; padding-top: 14px; border-top: 1px solid #d1d5db; font-size: 10px; color: #6b7280; text-align: center; }
</style>
</head>
<body>
  <div class="doc-head">
    <p class="eyebrow">DisasterMind // Post-Incident Analysis Report</p>
    <h1>${escapeHtml(reportTitle(data))}</h1>
    <div class="meta">Classification: Official &middot; Generated ${escapeHtml(formatGeneratedAt(generatedAt))} IST &middot; Audience: ${escapeHtml(audience)}</div>
  </div>
  ${sectionHtml}
  ${evidenceHtml}
  <div class="doc-foot">
    <p>This report was generated by DisasterMind AI v1.0. All autonomous decisions are logged in the tamper-proof audit trail.</p>
    <p>For queries: ${NDMA_EMAIL}</p>
  </div>
</body>
</html>`
}

/**
 * "Download PDF" — opens the print dialog on a print-ready rendering of the
 * report, where the user picks "Save as PDF". Dependency-free and works in
 * every browser. Falls back to a hidden iframe if the popup is blocked.
 */
function fileToDataUrl(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => typeof reader.result === 'string' ? resolve(reader.result) : reject(new Error('Image could not be read'))
    reader.onerror = () => reject(reader.error ?? new Error('Image could not be read'))
    reader.readAsDataURL(file)
  })
}

export async function downloadReportPdf(data: ReportExportData): Promise<void> {
  const printWindow = window.open('', '_blank')
  const evidenceSources = await Promise.all(
    data.siteEvidence.map((image) => fileToDataUrl(image.file).catch(() => image.previewUrl)),
  )
  const html = buildPrintableHtml(data, evidenceSources)

  if (printWindow) {
    printWindow.document.write(html)
    printWindow.document.close()
    printWindow.focus()
    const triggerPrint = () => window.setTimeout(() => printWindow.print(), 150)
    if (printWindow.document.readyState === 'complete') triggerPrint()
    else printWindow.addEventListener('load', triggerPrint, { once: true })
    return
  }

  // Popup blocked → print via a hidden iframe in the current document.
  const iframe = document.createElement('iframe')
  iframe.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0;'
  document.body.appendChild(iframe)
  const doc = iframe.contentWindow?.document
  if (!doc) return
  doc.open()
  doc.write(html)
  doc.close()
  iframe.onload = () => {
    iframe.contentWindow?.focus()
    iframe.contentWindow?.print()
    window.setTimeout(() => document.body.removeChild(iframe), 1500)
  }
}

/** Plain-text summary used as the email body for the NDMA dispatch. */
function buildPlainText(data: ReportExportData): string {
  const { incident, audience, generatedAt, sections, siteEvidence } = data
  const header = [
    'DISASTERMIND // POST-INCIDENT ANALYSIS REPORT',
    reportTitle(data),
    `Classification: OFFICIAL | Generated: ${formatGeneratedAt(generatedAt)} IST | Audience: ${audience}`,
    `Civilians reached: ${incident.civiliansReached.toLocaleString('en-IN')} of ${incident.civiliansAtRisk.toLocaleString('en-IN')} at risk`,
    '',
  ].join('\n')

  const body = sections
    .map((s) => `## ${s.title}\n${s.body.trim()}`)
    .join('\n\n')

  const evidence = siteEvidence.length > 0
    ? `\n\n## AFFECTED SITE EVIDENCE\n${siteEvidence.map((image, index) => {
      const metadata = [image.category, image.location, image.timestamp, image.latitude && image.longitude ? `${image.latitude}, ${image.longitude}` : undefined]
        .filter(Boolean)
        .join(' | ')
      return `${index + 1}. ${image.filename}${metadata ? ` — ${metadata}` : ''}${image.note ? `\n   ${image.note}` : ''}`
    }).join('\n')}`
    : ''

  return `${header}\n${body}${evidence}\n\n— Generated by DisasterMind AI v1.0`
}

/**
 * "Send to NDMA" — opens the operator's mail client with a dispatch to the
 * NDMA desk pre-filled (recipient, subject, plain-text report body). mailto
 * bodies are length-limited across clients, so the body is capped and the
 * full document is referenced as the attachable PDF.
 */
export function sendReportToNdma(data: ReportExportData): void {
  const subject = `[DisasterMind] Post-Incident Report — ${reportTitle(data)}`
  const full = buildPlainText(data)
  // Keep well under the ~2000-char practical mailto ceiling.
  const MAX = 1600
  const body =
    full.length > MAX
      ? `${full.slice(0, MAX)}\n\n…[truncated — attach the downloaded PDF for the full report]`
      : full

  const href = `mailto:${NDMA_EMAIL}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
  window.location.href = href
}
